language: android

cache:
    directories:
        - .nvm
        - node_modules

install:
    - nvm install 6
    - npm install --save ./cli-width-1.1.1.tgz
    - npm install -g nativescript

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
    - npm ls cli-width
    - ls -l ./node_modules/inquirer/node_modules
    - ls -l node_modules | grep -i cli-width
    - node -e 'console.log(tty.getWindowSize)'
    - node -e 'console.log(tty.getWindowSize && tty.getWindowSize())'
    - export CLI_WIDTH=30
    - echo $CLI_WIDTH
    - node a.js
    - pwd
    - tns -h
    - tns create app1
    - cd app1
    - ls -l
