language: android

cache:
    directories:
        - .nvm
        - node_modules

install:
    - nvm install 6
    - npm install -g nativescript

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
    - pwd
    - tns -h
    - tns create app1
    - cd app1
    - ls -l
