language: android

cache:
    directories:
        - .nvm
        - node_modules

install:
    - nvm install 4
    - npm install
    - cd node_modules
    - rm -rf mobile-cli-lib
    - git clone https://github.com/telerik/mobile-cli-lib.git
    - cd mobile-cli-lib
    - npm install
    - npm install -g grunt-cli
    - grunt
    - cd ../..

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
    - pwd
    - ls -al node_modules/.bin
    - ./node_modules/.bin/electron .
